- name: bug
  description: Something isn't working
  color: d42a34

- name: dependencies
  description: Related with project dependencies
  color: ffc0cb

- name: dependabot
  description: Related to dependabot
  color: f56cda

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: FFD827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: maintenance
  description: Package and maintenance related
  color: f78c37

- name: release
  description: Anything related to an incoming release
  color: ffffff

- name: testing
  description: Involves the development of new unit/functional tests
  color: bfe5bf

- name: major
  description: Major issue which may have to be subdivided into smaller ones
  color: 5319e7

- name: ci/cd
  description: Involves the GitHub workflow files
  color: b5f226

- name: future
  description: To be implemented in the future
  color: 5319e7

- name: windows
  description: Only observed in Windows
  color: 9fc5e8

- name: linux
  description: Only observed in Linux based platform
  color: a2c4c9

- name: docker
  description: Only observed in Mechanical docker image
  color: b6d7a8

- name: stale
  description: Stale issues will be closed after 60 days of inactivity
  color: f0dc82

- name: ansys-mechanical-bug
  description: Issues related to Ansys Mechanical, not PyMechanical
  color: B3B300

- name: fixed-in-261
  description: Issues fixed in Ansys Mechanical version 261
  color: FFD500

- name: fixed-in-awaiting-release
  description: Issues fixed in Ansys Mechanical future version
  color: FFDD33

- name: fixed-in-next-release
  description: Issues fixed in the upcoming Ansys Mechanical release
  color: FFEE66

- name: 24R2
  description: Bug observed in PyMechanical with Mechanical version 24R2
  color: 804000

- name: 25R1
  description: Bug observed in PyMechanical with Mechanical version 25R1
  color: CC6600

- name: 25R2
  description: Bug observed in PyMechanical with Mechanical version 25R2
  color: FF8000

- name: 26R1
  description: Bug observed in PyMechanical with Mechanical version 26R1
  color: FF9933

- name: resolved-awaiting-release
  description: Bug resolved and awaiting release of Ansys Mechanical
  color: FFA64D

- name: embedding
  description: Issues related to PyMechanical embedding
  color: 0095B3

- name: remote-session
  description: Issues related to remote sessions in PyMechanical
  color: 00B3B3

- name: skip-doc
  description: Skips the documentation build job in CI
  color: e4e669

- name: skip-test
  description: Skips the test job in CI
  color: e4e669