ci:
    autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'chore: pre-commit automatic update'
    autoupdate_schedule: weekly

exclude: '^tests/embedding/assets/.*$|^tests/parts/.*$'

repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # frozen: v0.16.5
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # frozen: v2.3.1
  hooks:
    - id: mypy
      additional_dependencies: [types-requests, types-tqdm]
      args: [--ignore-missing-imports]
      exclude: ^(tests|examples|doc)/

- repo: https://github.com/pre-commit-ci/pre-commit-ci-config
  rev: 500543de231a91e6157db630075d70320709b834  # frozen: v1.6.1
  hooks:
  -   id: check-pre-commit-ci-config

- repo: https://github.com/codespell-project/codespell
  rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
  hooks:
  - id: codespell
    args: ["--ignore-words-list", "addin", "--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "-w"]
    exclude: "doc/styles/typos\\.toml"

- repo: https://github.com/ansys/pre-commit-hooks
  rev: 55c5b6a5439abd847613579c6924da750e8b78b2  # frozen: v0.8.0
  hooks:
  - id: add-license-headers
    args:
    - --start_year=2022
  - id: tech-review
    args:
    - --product=mechanical

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace
  - id: check-added-large-files

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: c4654a7e007c9619a5eb63c39a456572a0fa1851  # frozen: 0.38.0
  hooks:
    - id: check-github-workflows

#  Disabling because of warnings
# - repo: https://github.com/zizmorcore/zizmor-pre-commit
#   rev: ea2eb407b4cbce87cf0d502f36578950494f5ac9  # frozen: v1.23.1
#   hooks:
#     - id: zizmor
#       args: ["--pedantic"]

# Security checks with bandit
- repo: https://github.com/PyCQA/bandit
  rev: 92ae8b82fb422a639f0ed8d99e96cea769594e08  # frozen: 1.9.4
  hooks:
    - id: bandit
      args: ['-c', 'pyproject.toml']
      additional_dependencies: ['bandit[toml]']

-   repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # frozen: v3.21.2
    hooks:
    -   id: pyupgrade
        args: ['--py312-plus']

- repo: https://github.com/crate-ci/typos
  rev: 7e42c54fbaa9738e072b11e93127845c36cef60d  # frozen: v1
  hooks:
    - id: typos
      args: ["--config", "doc/styles/typos.toml"]
      exclude: "doc/styles/config/vocabularies"