"""Sphinx documentation configuration file."""

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

from datetime import datetime
import os
from pathlib import Path
import warnings

from ansys_sphinx_theme import ansys_favicon, get_version_match
import pyvista
from pyvista.plotting.utilities.sphinx_gallery import DynamicScraper
import requests
from sphinx_gallery.sorting import FileNameSortKey

import ansys.mechanical.core as pymechanical
from ansys.mechanical.core.embedding.initializer import SUPPORTED_MECHANICAL_EMBEDDING_VERSIONS

# Documentation gallery: enables Sphinx-Gallery and embedded ``App`` instance
# reuse across gallery scripts. Per-constructor opt-out: ``App(..., reuse_instance=True)``.
pymechanical.BUILDING_GALLERY = True

# Ensure that offscreen rendering is used for docs generation
pyvista.OFF_SCREEN = True

# necessary when building the sphinx gallery
pyvista.BUILDING_GALLERY = True


# Whether or not to build the cheatsheet
BUILD_CHEATSHEET = os.environ.get("BUILD_CHEATSHEET", default="true") != "false"

# Whether or not to build the API reference (AutoAPI). AutoAPI generation can be slow,
# so you can disable it for faster local builds:
#   set BUILD_API=false        (Windows)
#   export BUILD_API=false     (Linux/macOS)
BUILD_API = "true"  # os.environ.get("BUILD_API", default="true") != "false"

# suppress annoying matplotlib bug
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    message="Matplotlib is currently using agg, which is a non-GUI backend, "
    "so cannot show the figure.",
)


# -- Project information -----------------------------------------------------

project = "ansys.mechanical.core"
copyright = f"(c) {datetime.now().year} ANSYS, Inc. All rights reserved"
author = "ANSYS Inc."
release = version = pymechanical.__version__
cname = os.getenv("DOCUMENTATION_CNAME", default="mechanical.docs.pyansys.com")
switcher_version = get_version_match(version)


# -- General configuration ---------------------------------------------------
# Sphinx extensions
extensions = [
    "jupyter_sphinx",
    "notfound.extension",
    "numpydoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_click",
    "ablog",
    "sphinxcontrib.mermaid",
]

if BUILD_API:
    extensions.insert(0, "ansys_sphinx_theme.extension.autoapi")

if pymechanical.BUILDING_GALLERY:
    extensions.append("sphinx_gallery.gen_gallery")
    extensions.append("pyvista.ext.plot_directive")
    extensions.append("pyvista.ext.viewer_directive")

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "numpy": ("https://numpy.org/devdocs", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "grpc": ("https://grpc.github.io/grpc/python/", None),
    "pypim": ("https://pypim.docs.pyansys.com/version/dev/", None),
    "pyvista": ("https://docs.pyvista.org/version/stable/", None),
}


suppress_warnings = ["label.*", "autoapi.python_import_resolution", "design.grid", "config.cache"]


# numpydoc configuration
numpydoc_use_plots = True
numpydoc_show_class_members = False
numpydoc_xref_param_type = True
numpydoc_validate = True
numpydoc_validation_checks = {
    "GL06",  # Found unknown section
    "GL07",  # Sections are in the wrong order.
    # "GL08",  # The object does not have a docstring
    "GL09",  # Deprecation warning should precede extended summary
    "GL10",  # reST directives {directives} must be followed by two colons
    "SS01",  # No summary found
    "SS02",  # Summary does not start with a capital letter
    # "SS03", # Summary does not end with a period
    "SS04",  # Summary contains heading whitespaces
    # "SS05", # Summary must start with infinitive verb, not third person
    "RT02",  # The first line of the Returns section should contain only the
    # type, unless multiple values are being returned"
}

numpydoc_validation_exclude = {  # set of regex
    # grpc files
    r"\.*pb2\.*",
}

# Favicon
html_favicon = ansys_favicon

# notfound.extension
notfound_template = "404.rst"
notfound_urls_prefix = "/../"

# static path
html_static_path = ["_static"]
html_css_files = ["css/blog.css"]
templates_path = ["_templates"]
# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "links.rst",
]

# If the API reference is not being built, exclude any stale, previously
# generated AutoAPI ``.rst`` files left over in ``doc/source/api`` from a prior
# build. Otherwise, Sphinx still discovers and writes them even though the
# ``autoapi`` extension itself is not loaded.
if not BUILD_API:
    exclude_patterns.append("api/**")

# Get the current Mechanical version
current_mechanical_version = next(iter(SUPPORTED_MECHANICAL_EMBEDDING_VERSIONS.keys()))

# Create a link directive to the Ansys help documentation to be used in ``helper_scripts.rst``
extlinks = {
    "ansyshelp": (
        "https://ansyshelp.ansys.com/public/account/secured?returnurl=/Views/Secured/corp/"
        f"v{current_mechanical_version}/en/act_script/%s",
        "ansyshelp %s",
    )
}

# Create the rst_epilog a variable, so you can add other epilog parts to it
rst_epilog = ""
# Read link all targets from file
with Path.open("links.rst") as f:
    rst_epilog += f.read()
# Replace the version placeholder in rst_epilog with the current Mechanical version
rst_epilog = rst_epilog.replace("%%VERSION%%", f"v{current_mechanical_version}")

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Copy button customization ---------------------------------------------------
# exclude traditional Python prompts from the copied code
copybutton_prompt_text = r">>> ?|\.\.\. "
copybutton_prompt_is_regexp = True

# -- Sphinx Gallery Options ---------------------------------------------------
sphinx_gallery_conf = {
    # convert rst to md for ipynb
    "pypandoc": True,
    # path to your examples scripts
    "examples_dirs": ["../../examples/"],
    # path where to save gallery generated examples
    "gallery_dirs": ["examples/gallery_examples"],  # Pattern to search for example files
    "filename_pattern": r"\.py",
    # Remove the "Download all examples" button from the top level gallery
    "download_all_examples": False,
    # Sort gallery example by file name instead of number of lines (default)
    "within_subsection_order": FileNameSortKey,
    # directory where function granular galleries are stored
    "backreferences_dir": None,
    # Modules for which function level galleries are created.  In
    "doc_module": "ansys-mechanical-core",
    "image_scrapers": (DynamicScraper(), "matplotlib"),
    # Files to ignore
    "ignore_pattern": "flycheck*",  # noqa: E501
    "thumbnail_size": (350, 350),
    "matplotlib_animations": True,
}

# -- Options for HTML output -------------------------------------------------
html_short_title = html_title = "PyMechanical"
html_theme = "ansys_sphinx_theme"
html_context = {
    "github_user": "pyansys",
    "github_repo": "pymechanical",
    "github_version": "main",
    "doc_path": "doc/source",
    "pyansys_tags": ["Structures"],
}
html_theme_options = {
    "logo": "pyansys",
    "switcher": {
        "json_url": f"https://{cname}/versions.json",
        "version_match": get_version_match(version),
    },
    "check_switcher": False,
    "github_url": "https://github.com/ansys/pymechanical",
    "show_prev_next": False,
    "show_breadcrumbs": True,
    "collapse_navigation": True,
    "use_edit_page_button": True,
    "header_links_before_dropdown": 5,  # number of links before the dropdown menu
    "navigation_dropdown": {
        "layout_file": "navbar.yml",
    },
    "additional_breadcrumbs": [
        ("PyAnsys", "https://docs.pyansys.com/"),
    ],
    "icon_links": [
        {
            "name": "Support",
            "url": "https://github.com/ansys/pymechanical/discussions",
            "icon": "fa fa-comment fa-fw",
        },
    ],
    "whatsnew": {
        "whatsnew_file_name": "../changelog.d/whatsnew.yml",
        "changelog_file_name": "changelog.rst",
        "sidebar_pages": ["changelog"],
    },
    "search_extra_sources": {
        "PyMechanical MCP": "https://mechanical-mcp.docs.pyansys.com/",
        "PyMechanical Examples: Remote session": "https://examples.mechanical.docs.pyansys.com/",
        "PyMechanical Advanced Examples: Embedding": "https://embedding.examples.mechanical.docs.pyansys.com/",
    },
    "mcp_server": {
        "url": "https://mechanical-mcp.docs.pyansys.com/",
        "project_name": "PyMechanical MCP Server",
    },
    "secondary_sidebar_items": [],
}


def intersphinx_pymechanical(switcher_version: str):
    """Auxiliary method to build the intersphinx mapping for PyMechanical.

    Parameters
    ----------
    switcher_version : str
        Version of the PyMechanical package.

    Returns
    -------
    str
        The intersphinx mapping for PyMechanical.

    Notes
    -----
    If the objects.inv file is not found whenever it is a release, the method
    will default to the "dev" version. If the objects.inv file is not found
    for the "dev" version, the method will return an empty string.
    """
    prefix = "https://mechanical.docs.pyansys.com/version"

    # Check if the object.inv file exists
    response = requests.get(f"{prefix}/{switcher_version}/objects.inv", timeout=5)

    if response.status_code == 404:
        if switcher_version == "dev":
            return ""
        else:
            return intersphinx_pymechanical("dev")
    else:
        return f"{prefix}/{switcher_version}"


if intersphinx_pymechanical(switcher_version):
    intersphinx_mapping["ansys.mechanical.core"] = (
        intersphinx_pymechanical(switcher_version),
        None,
    )


if BUILD_CHEATSHEET:
    html_theme_options["cheatsheet"] = {
        "file": "cheatsheet/cheat_sheet.qmd",
        "title": "PyMechanical cheat sheet",
    }

if BUILD_API:
    html_theme_options["ansys_sphinx_theme_autoapi"] = {"project": project}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "pymechanicaldoc"

html_sidebars = {
    "changelog": [],
    "contributing": [],
    "blog/*": [
        "ablog/postcard.html",
        "ablog/recentposts.html",
        "ablog/tagcloud.html",
        "ablog/categories.html",
        "ablog/archives.html",
    ],
}

# -- Mermaid configuration --------------------------------------------------
mermaid_output_format = "raw"
mermaid_dark_theme = "dark"
mermaid_light_theme = "default"

# -- ABlog configuration -----------------------------------------------------
blog_title = "PyMechanical Blog"
blog_baseurl = f"https://{cname}/"
blog_path = "blog"
blog_post_pattern = ["blog/*.rst"]
blog_feed_fulltext = True
blog_authors = {
    "ANSYS": ("ANSYS Inc.", None),
}

html_show_sourcelink = False

# -- Linkcheck config --------------------------------------------------------

linkcheck_ignore = [
    "https://github.com/ansys/pymechanical/pkgs/container/.*",
    "https://ansyshelp.ansys.com/*",
    "https://answers.microsoft.com/en-us/windows/forum/all/*",
    "https://download.ansys.com/*",
    "https://support.ansys.com/*",
    "https://discuss.ansys.com/*",
    "https://www.ansys.com/*",
    "https://developer.ansys.com/*",
    "../api/*",
]

linkcheck_anchors = False

linkcheck_exclude_documents = [
    "changelog",
]

# If we are on a release, we have to ignore the "release" URLs, since it is not
# available until the release is published.
switcher_version = get_version_match(version)
if switcher_version != "dev":
    linkcheck_ignore.append(
        f"https://github.com/ansys/pymechanical/releases/tag/v{pymechanical.__version__}"
    )


# -- Source-read substitution for version placeholders in code blocks ---------
# Standard RST substitutions (|name|) don't work inside code blocks.
# This hook replaces {mechanical_version} in the raw source before parsing,
# so it works everywhere including literal blocks and code-block directives.

# Custom autoapi index template: prepend _templates/autoapi/ to Jinja search
# paths so our index.rst is picked up before the theme's default, while the
# theme's python/class.rst and python/module.rst templates are still used.
_CUSTOM_AUTOAPI_TEMPLATES = str(Path(__file__).parent / "_templates" / "autoapi")


def _wrap_autoapi_jinja_env(app, config):
    """Prepend the custom autoapi template dir to the Jinja search path.

    This runs after the theme's config-inited handler (which sets
    ``autoapi_prepare_jinja_env``), so we can wrap its function rather than
    replace it, preserving the ``project_name`` / ``autoapi_depth`` globals.
    """
    original = config.autoapi_prepare_jinja_env

    def _wrapped(jinja_env):
        if original:
            original(jinja_env)
        loader = jinja_env.loader
        if hasattr(loader, "searchpath") and _CUSTOM_AUTOAPI_TEMPLATES not in loader.searchpath:
            loader.searchpath.insert(0, _CUSTOM_AUTOAPI_TEMPLATES)

    config["autoapi_prepare_jinja_env"] = _wrapped


def source_read_handler(app, docname, source):
    """Replace version placeholders in RST source before parsing."""
    source[0] = source[0].replace("{mechanical_version}", str(current_mechanical_version))
    source[0] = source[0].replace("{build_date}", "06/03/2026 09:51:20")


def setup(app):
    """Connect Sphinx events."""
    app.connect("source-read", source_read_handler)
    if BUILD_API:
        app.connect("config-inited", _wrap_autoapi_jinja_env)
