"""Sphinx documentation configuration file."""

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

from datetime import datetime
import os
from pathlib import Path
import warnings

from ansys_sphinx_theme import ansys_favicon, get_version_match
import pyvista
from pyvista.plotting.utilities.sphinx_gallery import DynamicScraper
from sphinx_gallery.sorting import FileNameSortKey

import ansys.mechanical.core as pymechanical
from ansys.mechanical.core.embedding.initializer import SUPPORTED_MECHANICAL_EMBEDDING_VERSIONS

# necessary when building the sphinx gallery
pymechanical.BUILDING_GALLERY = True

# Ensure that offscreen rendering is used for docs generation
pyvista.OFF_SCREEN = True

# necessary when building the sphinx gallery
pyvista.BUILDING_GALLERY = True


# Whether or not to build the cheatsheet
BUILD_CHEATSHEET = os.environ.get("BUILD_CHEATSHEET") == "true"

# suppress annoying matplotlib bug
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    message="Matplotlib is currently using agg, which is a non-GUI backend, "
    "so cannot show the figure.",
)

# -- Project information -----------------------------------------------------

project = "ansys.mechanical.core"
copyright = f"(c) {datetime.now().year} ANSYS, Inc. All rights reserved"
author = "ANSYS Inc."
release = version = pymechanical.__version__
cname = os.getenv("DOCUMENTATION_CNAME", default="mechanical.docs.pyansys.com")


# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# -- General configuration ---------------------------------------------------
# Sphinx extensions
extensions = [
    "ansys_sphinx_theme.extension.autoapi",
    "jupyter_sphinx",
    "notfound.extension",
    "numpydoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
    "sphinx_design",
    "pyvista.ext.plot_directive",
    "pyvista.ext.viewer_directive",
    "sphinx_click",
]

if pymechanical.BUILDING_GALLERY:
    extensions.append("sphinx_gallery.gen_gallery")

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "numpy": ("https://numpy.org/devdocs", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
    "grpc": ("https://grpc.github.io/grpc/python/", None),
    "pypim": ("https://pypim.docs.pyansys.com/version/dev/", None),
}

suppress_warnings = ["label.*", "autoapi.python_import_resolution", "design.grid", "config.cache"]
# supress_warnings = ["ref.option"]


# numpydoc configuration
numpydoc_use_plots = True
numpydoc_show_class_members = False
numpydoc_xref_param_type = True
numpydoc_validate = True
numpydoc_validation_checks = {
    "GL06",  # Found unknown section
    "GL07",  # Sections are in the wrong order.
    # "GL08",  # The object does not have a docstring
    "GL09",  # Deprecation warning should precede extended summary
    "GL10",  # reST directives {directives} must be followed by two colons
    "SS01",  # No summary found
    "SS02",  # Summary does not start with a capital letter
    # "SS03", # Summary does not end with a period
    "SS04",  # Summary contains heading whitespaces
    # "SS05", # Summary must start with infinitive verb, not third person
    "RT02",  # The first line of the Returns section should contain only the
    # type, unless multiple values are being returned"
}

numpydoc_validation_exclude = {  # set of regex
    # grpc files
    r"\.*pb2\.*",
}

# Favicon
html_favicon = ansys_favicon

# notfound.extension
notfound_template = "404.rst"
notfound_urls_prefix = "/../"

# static path
html_static_path = ["_static"]
templates_path = ["_templates"]
# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "links.rst",
]

# Get the current Mechanical version
current_mechanical_version = next(iter(SUPPORTED_MECHANICAL_EMBEDDING_VERSIONS.keys()))

# Create a link directive to the Ansys help documentation to be used in ``helper_scripts.rst``
extlinks = {
    "ansyshelp": (
        "https://ansyshelp.ansys.com/public/account/secured?returnurl=/Views/Secured/corp/"
        f"v{current_mechanical_version}/en/act_script/%s",
        "ansyshelp %s",
    )
}

# Create the rst_epilog a variable, so you can add other epilog parts to it
rst_epilog = ""
# Read link all targets from file
with Path.open("links.rst") as f:
    rst_epilog += f.read()
# Replace the version placeholder in rst_epilog with the current Mechanical version
rst_epilog = rst_epilog.replace("%%VERSION%%", f"v{current_mechanical_version}")

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Copy button customization ---------------------------------------------------
# exclude traditional Python prompts from the copied code
copybutton_prompt_text = r">>> ?|\.\.\. "
copybutton_prompt_is_regexp = True

# -- Sphinx Gallery Options ---------------------------------------------------
sphinx_gallery_conf = {
    # convert rst to md for ipynb
    "pypandoc": True,
    # path to your examples scripts
    "examples_dirs": ["../../examples/"],
    # path where to save gallery generated examples
    "gallery_dirs": ["examples/gallery_examples"],  # Pattern to search for example files
    "filename_pattern": r"\.py",
    # Remove the "Download all examples" button from the top level gallery
    "download_all_examples": False,
    # Sort gallery example by file name instead of number of lines (default)
    "within_subsection_order": FileNameSortKey,
    # directory where function granular galleries are stored
    "backreferences_dir": None,
    # Modules for which function level galleries are created.  In
    "doc_module": "ansys-mechanical-core",
    "image_scrapers": (DynamicScraper(), "matplotlib"),
    # Files to ignore
    "ignore_pattern": """flycheck*| \
        fracture_analysis_contact_debonding.py| \
        harmonic_acoustics.py| \
        modal_acoustics_analysis.py""",
    "thumbnail_size": (350, 350),
}

# -- Options for HTML output -------------------------------------------------
html_short_title = html_title = "PyMechanical"
html_theme = "ansys_sphinx_theme"
html_context = {
    "github_user": "pyansys",
    "github_repo": "pymechanical",
    "github_version": "main",
    "doc_path": "doc/source",
    "pyansys_tags": ["Structures"],
}
html_theme_options = {
    "logo": "pyansys",
    "switcher": {
        "json_url": f"https://{cname}/versions.json",
        "version_match": get_version_match(version),
    },
    "check_switcher": False,
    "github_url": "https://github.com/ansys/pymechanical",
    "show_prev_next": False,
    "show_breadcrumbs": True,
    "collapse_navigation": True,
    "use_edit_page_button": True,
    "header_links_before_dropdown": 5,  # number of links before the dropdown menu
    "additional_breadcrumbs": [
        ("PyAnsys", "https://docs.pyansys.com/"),
    ],
    "icon_links": [
        {
            "name": "Support",
            "url": "https://github.com/ansys/pymechanical/discussions",
            "icon": "fa fa-comment fa-fw",
        },
    ],
    "whatsnew": {
        "whatsnew_file_name": "../changelog.d/whatsnew.yml",
        "changelog_file_name": "changelog.rst",
        "sidebar_pages": ["changelog", "index"],
    },
    "ansys_sphinx_theme_autoapi": {"project": project, "templates": "_templates/autoapi"},
}

if BUILD_CHEATSHEET:
    html_theme_options["cheatsheet"] = {
        "file": "cheatsheet/cheat_sheet.qmd",
        "title": "PyMechanical cheat sheet",
    }

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "pymechanicaldoc"

html_sidebars = {
    "changelog": [],
    "contributing": [],
}

html_show_sourcelink = False

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        f"pymechanical-Documentation-{version}.tex",
        "ansys.mechanical.core Documentation",
        author,
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "ansys.mechanical.core", "ansys.mechanical.core Documentation", [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "ansys.mechanical.core",
        "ansys.mechanical.core Documentation",
        author,
        "ansys.mechanical.core",
        "Pythonic interface to Mechanical using gRPC",
        "Engineering Software",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

# -- Linkcheck config --------------------------------------------------------

linkcheck_ignore = [
    "https://github.com/ansys/pymechanical/pkgs/container/.*",
    "https://ansyshelp.ansys.com/*",
    "https://ansysaccount.b2clogin.com/*",
    "https://answers.microsoft.com/en-us/windows/forum/all/*",
    "https://download.ansys.com/*",
    "https://support.ansys.com/*",
    "https://discuss.ansys.com/*",
    "https://www.ansys.com/*",
    "../api/*",  # Remove this after release 0.10.12
    "api/*",
    "path.html",
    "user_guide_embedding/*",
    "changelog.html",
]

linkcheck_anchors = False

# If we are on a release, we have to ignore the "release" URLs, since it is not
# available until the release is published.
switcher_version = get_version_match(version)
if switcher_version != "dev":
    linkcheck_ignore.append(
        f"https://github.com/ansys/pymechanical/releases/tag/v{pymechanical.__version__}"
    )
