blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/ansys/pymechanical/discussions
    about: For general questions and discussions, please use GitHub Discussions.
