version: '3.3'

# This is a docker-compose file that launches a remote Mechanical instance in a Dockerized environment.
# You can connect to this instance through port 10000.
#
# For the license, you need to provide the hostname of the license server.
#
# REQUIREMENTS:
# =============
#
# - docker
# - docker images from ghcr.io (you might need to do 'docker login ghcr.io' first)
#
# USAGE:
# ======
#
# 1. You need an environment variable named ANSYSLMD_LICENSE_FILE that points to the license server. For example:
#
#     export ANSYSLMD_LICENSE_FILE=1055@mylicensehost
#
# 2. Run the following command:
#
#     docker-compose up
#
# Optionally you can specify the '-d' flag for detaching mode. (The container will run in the background.)
#
#
# NOTES:
# ======
#
# - The docker image is based on the Mechanical Ubuntu docker image from Ansys.
# - The entrypoint is defined in the Docker image.
# - If you need to run a license server, look at the 'docker-compose.license_server.yml' file.
#   In that case, the command would be:
#
#    docker-compose -f docker-compose.yml -f docker-compose.license_server.yml up
#
#
# - If you want to mount the local directory, add the 'volumes' section to the 'mechanical' service.
#
#      volumes:
#        - ./:/local
#

services:
  mechanical:
    restart: always
    shm_size: '8gb'
    container_name: mechanical
    mem_reservation: 8g
    environment:
      - ANSYSLMD_LICENSE_FILE=${ANSYSLMD_LICENSE_FILE}
    ports:
      - '10000:10000'
    image: 'ghcr.io/ansys/mechanical:25.1.0'
    user: "0:0"
    # entrypoint: "/bin/bash tini -- xvfb-run ./.workbench -dsapplet -AppModeMech -b -grpc 10000"

