# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.mechanical.core import mechanical_pb2 as mechanical__pb2


class MechanicalServiceStub(object):
    """Interface of the Mechanical grpc service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunJScript = channel.unary_stream(
            "/ansys.api.mechanical.v1.MechanicalService/RunJScript",
            request_serializer=mechanical__pb2.RunScriptRequest.SerializeToString,
            response_deserializer=mechanical__pb2.RunScriptResponse.FromString,
        )
        self.RunPythonScript = channel.unary_stream(
            "/ansys.api.mechanical.v1.MechanicalService/RunPythonScript",
            request_serializer=mechanical__pb2.RunScriptRequest.SerializeToString,
            response_deserializer=mechanical__pb2.RunScriptResponse.FromString,
        )
        self.Shutdown = channel.unary_unary(
            "/ansys.api.mechanical.v1.MechanicalService/Shutdown",
            request_serializer=mechanical__pb2.ShutdownRequest.SerializeToString,
            response_deserializer=mechanical__pb2.ShutdownResponse.FromString,
        )
        self.UploadFile = channel.stream_unary(
            "/ansys.api.mechanical.v1.MechanicalService/UploadFile",
            request_serializer=mechanical__pb2.FileUploadRequest.SerializeToString,
            response_deserializer=mechanical__pb2.FileUploadResponse.FromString,
        )
        self.DownloadFile = channel.unary_stream(
            "/ansys.api.mechanical.v1.MechanicalService/DownloadFile",
            request_serializer=mechanical__pb2.FileDownloadRequest.SerializeToString,
            response_deserializer=mechanical__pb2.FileDownloadResponse.FromString,
        )


class MechanicalServiceServicer(object):
    """Interface of the Mechanical grpc service."""

    def RunJScript(self, request, context):
        """Run jscript block."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunPythonScript(self, request, context):
        """Run python script block."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Shutdown(self, request, context):
        """Exit Mechanical."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UploadFile(self, request_iterator, context):
        """Upload file to Mechanical grpc server."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DownloadFile(self, request, context):
        """Download file from Mechanical grpc server."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MechanicalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunJScript": grpc.unary_stream_rpc_method_handler(
            servicer.RunJScript,
            request_deserializer=mechanical__pb2.RunScriptRequest.FromString,
            response_serializer=mechanical__pb2.RunScriptResponse.SerializeToString,
        ),
        "RunPythonScript": grpc.unary_stream_rpc_method_handler(
            servicer.RunPythonScript,
            request_deserializer=mechanical__pb2.RunScriptRequest.FromString,
            response_serializer=mechanical__pb2.RunScriptResponse.SerializeToString,
        ),
        "Shutdown": grpc.unary_unary_rpc_method_handler(
            servicer.Shutdown,
            request_deserializer=mechanical__pb2.ShutdownRequest.FromString,
            response_serializer=mechanical__pb2.ShutdownResponse.SerializeToString,
        ),
        "UploadFile": grpc.stream_unary_rpc_method_handler(
            servicer.UploadFile,
            request_deserializer=mechanical__pb2.FileUploadRequest.FromString,
            response_serializer=mechanical__pb2.FileUploadResponse.SerializeToString,
        ),
        "DownloadFile": grpc.unary_stream_rpc_method_handler(
            servicer.DownloadFile,
            request_deserializer=mechanical__pb2.FileDownloadRequest.FromString,
            response_serializer=mechanical__pb2.FileDownloadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ansys.api.mechanical.v1.MechanicalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MechanicalService(object):
    """Interface of the Mechanical grpc service."""

    @staticmethod
    def RunJScript(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ansys.api.mechanical.v1.MechanicalService/RunJScript",
            mechanical__pb2.RunScriptRequest.SerializeToString,
            mechanical__pb2.RunScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RunPythonScript(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ansys.api.mechanical.v1.MechanicalService/RunPythonScript",
            mechanical__pb2.RunScriptRequest.SerializeToString,
            mechanical__pb2.RunScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Shutdown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ansys.api.mechanical.v1.MechanicalService/Shutdown",
            mechanical__pb2.ShutdownRequest.SerializeToString,
            mechanical__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UploadFile(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/ansys.api.mechanical.v1.MechanicalService/UploadFile",
            mechanical__pb2.FileUploadRequest.SerializeToString,
            mechanical__pb2.FileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DownloadFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ansys.api.mechanical.v1.MechanicalService/DownloadFile",
            mechanical__pb2.FileDownloadRequest.SerializeToString,
            mechanical__pb2.FileDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
