# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mechanical.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mechanical.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\nMechanical',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10mechanical.proto\"&\n\x10RunScriptRequest\x12\x12\n\nscriptCode\x18\x01 \x01(\t\")\n\x11RunScriptResponse\x12\x14\n\x0cscriptResult\x18\x01 \x01(\t\"\x12\n\x10ShutdowntRequest\"\x13\n\x11ShutdowntResponse2\xb5\x01\n\x11MechanicalService\x12\x33\n\nRunJScript\x12\x11.RunScriptRequest\x1a\x12.RunScriptResponse\x12\x38\n\x0fRunPythonScript\x12\x11.RunScriptRequest\x1a\x12.RunScriptResponse\x12\x31\n\x08Shutdown\x12\x11.ShutdowntRequest\x1a\x12.ShutdowntResponseB\r\xaa\x02\nMechanicalb\x06proto3'
)




_RUNSCRIPTREQUEST = _descriptor.Descriptor(
  name='RunScriptRequest',
  full_name='RunScriptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scriptCode', full_name='RunScriptRequest.scriptCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=58,
)


_RUNSCRIPTRESPONSE = _descriptor.Descriptor(
  name='RunScriptResponse',
  full_name='RunScriptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scriptResult', full_name='RunScriptResponse.scriptResult', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=101,
)


_SHUTDOWNTREQUEST = _descriptor.Descriptor(
  name='ShutdowntRequest',
  full_name='ShutdowntRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=121,
)


_SHUTDOWNTRESPONSE = _descriptor.Descriptor(
  name='ShutdowntResponse',
  full_name='ShutdowntResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['RunScriptRequest'] = _RUNSCRIPTREQUEST
DESCRIPTOR.message_types_by_name['RunScriptResponse'] = _RUNSCRIPTRESPONSE
DESCRIPTOR.message_types_by_name['ShutdowntRequest'] = _SHUTDOWNTREQUEST
DESCRIPTOR.message_types_by_name['ShutdowntResponse'] = _SHUTDOWNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunScriptRequest = _reflection.GeneratedProtocolMessageType('RunScriptRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNSCRIPTREQUEST,
  '__module__' : 'mechanical_pb2'
  # @@protoc_insertion_point(class_scope:RunScriptRequest)
  })
_sym_db.RegisterMessage(RunScriptRequest)

RunScriptResponse = _reflection.GeneratedProtocolMessageType('RunScriptResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNSCRIPTRESPONSE,
  '__module__' : 'mechanical_pb2'
  # @@protoc_insertion_point(class_scope:RunScriptResponse)
  })
_sym_db.RegisterMessage(RunScriptResponse)

ShutdowntRequest = _reflection.GeneratedProtocolMessageType('ShutdowntRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNTREQUEST,
  '__module__' : 'mechanical_pb2'
  # @@protoc_insertion_point(class_scope:ShutdowntRequest)
  })
_sym_db.RegisterMessage(ShutdowntRequest)

ShutdowntResponse = _reflection.GeneratedProtocolMessageType('ShutdowntResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNTRESPONSE,
  '__module__' : 'mechanical_pb2'
  # @@protoc_insertion_point(class_scope:ShutdowntResponse)
  })
_sym_db.RegisterMessage(ShutdowntResponse)


DESCRIPTOR._options = None

_MECHANICALSERVICE = _descriptor.ServiceDescriptor(
  name='MechanicalService',
  full_name='MechanicalService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunJScript',
    full_name='MechanicalService.RunJScript',
    index=0,
    containing_service=None,
    input_type=_RUNSCRIPTREQUEST,
    output_type=_RUNSCRIPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunPythonScript',
    full_name='MechanicalService.RunPythonScript',
    index=1,
    containing_service=None,
    input_type=_RUNSCRIPTREQUEST,
    output_type=_RUNSCRIPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='MechanicalService.Shutdown',
    index=2,
    containing_service=None,
    input_type=_SHUTDOWNTREQUEST,
    output_type=_SHUTDOWNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MECHANICALSERVICE)

DESCRIPTOR.services_by_name['MechanicalService'] = _MECHANICALSERVICE

# @@protoc_insertion_point(module_scope)
