name: >
  Set up Python

description: |
  Sets up Python on the Mechanical containers.

inputs:

  # Required inputs
  container-sha:
    description: >
      The SHA of the test container. For example, it would be the digest SHA of ghcr.io/ansys/mechanical:25.2.0
    required: true
    type: string

  python-version:
    description: >
      Python version to set up. For example, 3.10
    required: true
    type: string

  is-dev-container:
    description: >
      Whether the container is a dev container (contains "Dev" in its name).
    required: true
    type: boolean

  # Optional inputs
  python-version-patch:
    description: >
      The Python version to set up with the patch specified. For example, 3.10.0
    required: false
    type: string
    default: ""

  enable-optimizations:
    description: >
      Whether to enable optimizations when building Python from source.
      Defaults to true.
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: "Install necessary packages"
      shell: bash
      run: |
        # Install sqlite3, libsqlite3-dev, and lsb-release
        apt-get update
        apt-get install sqlite3 libsqlite3-dev lsb-release -y

    - name: "Set up Python ${{ inputs.python-version }}"
      if: inputs.is-dev-container == 'true'
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Get most recent Python version
      if: inputs.is-dev-container == 'false'
      shell: bash
      run: |
          declare -A python_versions=(["3.10"]="3.10.18" ["3.11"]="3.11.13" ["3.12"]="3.12.11" ["3.13"]="3.13.7")

          # Get the Python version inputs
          python_version_input="${{ inputs.python-version }}"
          python_version_patch_input="${{ inputs.python-version-patch }}"

          if [ -n "$python_version_patch_input" ]; then
            echo "PYTHON_VERSION_PATCH=$python_version_patch_input" >> "$GITHUB_ENV"
          else
            if [[ -v python_versions["$python_version_input"] ]]; then
              echo "PYTHON_VERSION_PATCH=${python_versions[$python_version_input]}" >> "$GITHUB_ENV"
            else
              echo "Key '$python_version_input' does not exist in the hashmap."
              echo "The available Python versions are: ${!python_versions[@]}"
              exit 1
            fi
          fi

    - name: "Cache Python directories"
      id: cache-python
      if: inputs.is-dev-container == 'false'
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          /usr/local/bin
          /usr/local/include
          /usr/local/lib
        key: python${{ inputs.python-version }}-dirs-${{ inputs.container-sha }}
        restore-keys: |
          python${{ inputs.python-version }}-dirs

    - name: "Confirm Python is installed"
      if: ${{ steps.cache-python.outputs.cache-hit == 'true' && inputs.is-dev-container == 'false' }}
      shell: bash
      run: |
        python_location=$(which python${{ inputs.python-version }})
        echo "Python ${{ inputs.python-version }} found at $python_location"

    - name: "Install Python ${{ env.PYTHON_VERSION_PATCH }}"
      if: ${{ steps.cache-python.outputs.cache-hit != 'true' && inputs.is-dev-container == 'false' }}
      shell: bash
      run: |
        # Update package lists
        apt update

        # Install dependencies to build Python
        apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev -y

        # Download the specified Python version from python.org
        version=${{ env.PYTHON_VERSION_PATCH }}
        wget https://www.python.org/ftp/python/$version/Python-$version.tgz

        # Extract the downloaded tarball
        tar -xf Python-$version.tgz

        # Check the required dependencies of the Python install
        cd Python-$version/

        if [ "${{ inputs.enable-optimizations }}" = true ]; then
          optimization_flag="--enable-optimizations"
        else
          optimization_flag=""
        fi
        ./configure $optimizations_flag

        # Build Python
        make -j $(nproc)

        # Install Python
        make altinstall

    - name: "Configure Python"
      shell: bash
      run: |
        # Get the location of the installed Python version
        python_location=$(which python${{ inputs.python-version }})

        # Link python to the installed version
        ln -s $python_location /usr/bin/python

        # Verify Python installation
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip
        python -m venv /env

    - name: "Check the virtual environment Python can be used"
      shell: bash
      run: |
        . /env/bin/activate

        env_python_check=$(which python)
        echo "Using python from $env_python_check"

        if [[ $env_python_check =~ "env" ]]; then
          echo "Using virtual environment"
        else
          echo "Not using virtual environment: $env_python_check"
          exit 1
        fi
