name: 'Docker Login'
description: 'Login to GitHub Container Registry'
runs:
  using: 'composite'
  steps:
    - name: Login in Github Container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
