name: GitHub CI

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * *'  # UTC time, may start 5-15 mins later than scheduled time
  # registry_package:
    # Run workflow when package is published or updated
    # types: [published]
  push:
    tags:
      - "*"
    branches:
      - main
      - release/*

env:
  PYMECHANICAL_PORT: 10000  # default won't work on GitHub runners
  PYMECHANICAL_START_INSTANCE: false
  DOCKER_PACKAGE: ghcr.io/ansys/mechanical
  DOCKER_MECH_CONTAINER_NAME: mechanical
  PACKAGE_NAME: ansys-mechanical-core
  DOCUMENTATION_CNAME: mechanical.docs.pyansys.com
  MAIN_PYTHON_VERSION: '3.10'
  # LATEST_STABLE_REVN and its Docker image are used in pull requests
  LATEST_STABLE_REVN: '241'
  LATEST_STABLE_DOCKER_IMAGE_VERSION: '24.1.0'
  # DEV_REVN & its Docker image are used in scheduled or registry package runs
  DEV_REVN: '242'
  DEV_DOCKER_IMAGE_VERSION: '24.2.0'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_HOST_URL: ${{ vars.MEILISEARCH_HOST_URL }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc-build:
    name: Documentation
    runs-on: public-ubuntu-latest-8-cores #ubuntu-latest
    container:
      image: ghcr.io/ansys/mechanical:24.1.0
      options: --entrypoint /bin/bash
    needs: []

    steps:

      - name: Install Git and checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          apt update
          apt install --reinstall ca-certificates
          apt install software-properties-common -y
          add-apt-repository ppa:deadsnakes/ppa -y
          apt install -y python3.10 python3.10-venv
          python3.10 -m venv /env

      - name: Install system dependencies
        run: |
          apt update
          apt install -y sudo curl lsb-release
          apt install -y zip pandoc libgl1-mesa-glx mesa-utils xvfb texlive-latex-extra latexmk nodejs npm graphviz
          apt install -y tini
          npm install -g @mermaid-js/mermaid-cli

      - name: Install Python requirements
        run: |
          . /env/bin/activate
          pip install -e .[doc]

      - name: Build docs
        env:
          SPHINXOPTS: '-j auto'
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}
          ANSYS_WORKBENCH_LOGGING_FILTER_LEVEL: 0
        run: |
          . /env/bin/activate
          # Create html or pdf doc
          create_doc() {
            # Need to unset PYMECHANICAL_PORT and PYMECHANICAL_START_INSTANCE when running code containing remote sessions
            unset PYMECHANICAL_PORT
            unset PYMECHANICAL_START_INSTANCE

            output_file=doc_$1_output.txt
            tini -s xvfb-run mechanical-env make -C doc 2>&1 html | tee $output_file
            echo done running make
            validate_output $output_file
          }

          # Validate that the html or pdf build succeeded
          validate_output() {
            echo "validating output of build"
            # $1 is the file we are checking
            # cat $1
            #
            # Check if "build succeeded" string is present in doc_build_output.txt
            #
            if grep -q "build succeeded" $1; then
              echo "Documentation building succeeded"
            else
              echo "Documentation building failed"
              exit 1
            fi
          }

          # Create the html doc & validate results
          create_doc html
