name: GitHub CI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
      - release/*

permissions: {}

jobs:
  test:
    name: Testing running on custom container
    runs-on: windows-latest
    container:
      image: mcr.microsoft.com/dotnet/aspnet:8.0-preview-windowsservercore-ltsc2022
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
