name: Coverage # zizmor: ignore[concurrency-limits]

on:
  workflow_call:
    inputs:
      main-python-version:
        type: string
        required: true
      package-name:
        type: string
        required: true

permissions: {}

jobs:
  coverage:
    name: Merging coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ inputs.main-python-version }}

      - name: Install coverage
        run: |
          rm -rf ./env
          python -m pip install -U pip
          pip install coverage
          pip install -e .

      - name: Create common coverage directory
        run: mkdir cov-dir

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-file-tests-embedding
          path: cov-dir/embedding

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-file-tests-embedding-scripts
          path: cov-dir/embedding-scripts

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-file-tests-remote-session-launch
          path: cov-dir/launch

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-file-tests
          path: cov-dir/normal

      - name: Display structure of downloaded files
        run: ls -Ra

      - name: Move files to common location
        run: |
          mv cov-dir/embedding/.coverage .coverage.Embedding
          mv cov-dir/embedding-scripts/.coverage .coverage.EmbeddingScripts
          mv cov-dir/launch/.coverage .coverage.Launch
          mv cov-dir/normal/.coverage .coverage.Normal
          rm -rf cov-dir

      - name: Generate .coveragerc file
        run: |
          cat > .coveragerc << 'EOF'

          # .coveragerc to control coverage.py
          [run]
          relative_files = True

          [paths]
          source =
              src/ansys/mechanical
              /opt/hostedtoolcache/**/ansys/mechanical
              /usr/local/lib/**/ansys/mechanical
              .venv/lib/**/ansys/mechanical
              /env/lib/**/ansys/mechanical
          EOF

      - name: Run coverage merge and show results
        run: |
          coverage combine --keep --debug=pathmap --rcfile=.coveragerc
          coverage report
          coverage html -d .coverage-combined/html
          coverage xml -o .coverage-combined/xml

      - name: Upload combined coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          include-hidden-files: true
          name: combined-coverage-results
          path: .coverage-combined
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .coverage-combined/xml

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: '.coverage-combined/xml'
