name: Style & Security Checks # zizmor: ignore[concurrency-limits]

on:
  workflow_call:

permissions: {}

jobs:
  style:
    name: Code style
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: PyAnsys code style checks
        uses: ansys/actions/code-style@12ca08fd7f0caa52076cca15c5621482646f8560 # v10.3.1
        with:
          python-version: ${{ vars.MAIN_PYTHON_VERSION }}

  doc-style:
    name: Documentation Style Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: PyAnsys documentation style checks
        uses: ansys/actions/doc-style@12ca08fd7f0caa52076cca15c5621482646f8560 # v10.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  check-vulnerabilities:
    name: Check Vulnerabilities
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: PyAnsys Vulnerability check (on main)
        if: github.ref == 'refs/heads/main'
        uses: ansys/actions/check-vulnerabilities@12ca08fd7f0caa52076cca15c5621482646f8560 # v10.3.1
        with:
          python-version: ${{ vars.MAIN_PYTHON_VERSION }}
          python-package-name: ${{ vars.PACKAGE_NAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: PyAnsys Vulnerability check (on dev mode)
        if: github.ref != 'refs/heads/main'
        uses: ansys/actions/check-vulnerabilities@12ca08fd7f0caa52076cca15c5621482646f8560 # v10.3.1
        with:
          python-version: ${{ vars.MAIN_PYTHON_VERSION }}
          python-package-name: ${{ vars.PACKAGE_NAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          dev-mode: true

  check-actions-security:
    name: "Check Actions Security"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/check-actions-security@12ca08fd7f0caa52076cca15c5621482646f8560 # v10.3.1
        with:
          generate-summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          auditing-level: 'high'
          trust-ansys-actions: true
